-- MySQL Script generated by MySQL Workbench
-- Mon Mar 25 10:05:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NULL,
  `birthDate` DATE NOT NULL,
  `birthPlace` VARCHAR(45) NULL,
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Group` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Group` (
  `idGroup` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  UNIQUE INDEX `idGroup_UNIQUE` (`idGroup` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Media` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Media` (
  `idMedia` INT NOT NULL AUTO_INCREMENT,
  `mediaUrl` VARCHAR(45) NOT NULL,
  `post` INT NOT NULL,
  PRIMARY KEY (`idMedia`),
  UNIQUE INDEX `idMedia_UNIQUE` (`idMedia` ASC) VISIBLE,
  UNIQUE INDEX `post_UNIQUE` (`post` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visibility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Visibility` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Visibility` (
  `idVisibility` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVisibility`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `text` VARCHAR(500) NULL,
  `user` INT NOT NULL,
  `visibility` INT NOT NULL,
  `group` INT NULL,
  PRIMARY KEY (`idPost`),
  UNIQUE INDEX `idPost_UNIQUE` (`idPost` ASC) VISIBLE,
  INDEX `fk_Post_Group_idx` (`group` ASC) VISIBLE,
  CONSTRAINT `fk_Post_Media`
    FOREIGN KEY (`idPost`)
    REFERENCES `mydb`.`Media` (`post`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Post_Visibility`
    FOREIGN KEY (`visibility`)
    REFERENCES `mydb`.`Visibility` (`idVisibility`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_User`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Post_Group`
    FOREIGN KEY (`group`)
    REFERENCES `mydb`.`Group` (`idGroup`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FriendshipRequest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FriendshipRequest` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FriendshipRequest` (
  `idFriendshipRequest` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `user_sender` INT NOT NULL,
  `user_receiver` INT NOT NULL,
  PRIMARY KEY (`idFriendshipRequest`),
  UNIQUE INDEX `idFriendshipRequest_UNIQUE` (`idFriendshipRequest` ASC) VISIBLE,
  INDEX `SentRequest_idx` (`user_sender` ASC) VISIBLE,
  INDEX `RecievedRequest_idx` (`user_receiver` ASC) VISIBLE,
  CONSTRAINT `RecievedRequest`
    FOREIGN KEY (`user_receiver`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SentRequest`
    FOREIGN KEY (`user_sender`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserGroup` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserGroup` (
  `user` INT NOT NULL,
  `group` INT NOT NULL,
  PRIMARY KEY (`user`, `group`),
  INDEX `fk_UserGroup_Group_idx` (`group` ASC) VISIBLE,
  CONSTRAINT `fk_UserGroup_User`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UserGroup_Group`
    FOREIGN KEY (`group`)
    REFERENCES `mydb`.`Group` (`idGroup`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Friendship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Friendship` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Friendship` (
  `user1` INT NOT NULL,
  `user2` INT NOT NULL,
  PRIMARY KEY (`user1`, `user2`),
  INDEX `Friendship2_idx` (`user2` ASC) VISIBLE,
  CONSTRAINT `Friendship1`
    FOREIGN KEY (`user1`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Friendship2`
    FOREIGN KEY (`user2`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
DROP VIEW IF EXISTS `mydb`.`view1` ;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
